### ISSUE TITLE
Test handling of -x and -h notation

### ISSUE THREAD

**Issue by simonsmithdatascience** [giellalt/lang-epo#1]
How to convert texts in -x or -h notation to  "ĉapelo," or hat, form? Esperanto has the following unusual letters: ĉ, ĝ, ĥ, ĵ, ŝ, ŭ, and the diacritics above the Roman letters are the "ĉapeloj." The hats can be difficult to type, so writers will often use workarounds with an 'x' or an 'h' after the letter to be modified. Example: "cxapeloj" or "chapeloj" denote "ĉapeloj." The letter 'h' is a character in Esperanto (ex, 'horo' is 'hour'), but 'x' is not.

In src/orthography, I wrote a regex file for changing 'cx' and 'ch' to 'ĉ' but don't know how to test it. Is this something that should be done in src/orthography or in a twolc file elsewhere?

**Comment by snomos** [comment]
GiellaLT admin here (sorry @reynoldsnlp if I answer things you intend to answer):

`src/orthography/` is the correct place, and if you store your regex in the file `spellrelax.regex`, it will automatically be applied to the analyser fst `src/analyser-gt-desc.hfst`. Then you can test it with the following command (this is all assuming you are using hfst - if you are using xfst or foma, replace with the similar tools):

```sh
echo 'cxapeloj' | hfst-lookup -q src/analyser-gt-desc.hfst
```

You should get an analysis, and the lemma should be 'ĉapeloj'. Hope this helps 🙂

**Comment by simonsmithdatascience** [comment]
That works now, thank you so much!
